#  _config.yml has all the global configuration

theme: jekyll-theme-midnight

title: AC's Techshots
description: Technical notes and titbits of everyday programmer's life.
url: https://chakrabar.github.io
author: Arghya C

thumbnail_src: https://chakrabar.github.io/assets/images/github_profile.png

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project. Can use "folder_name" OR "section/*/special-page.html"
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"