theme: jekyll-theme-architect

title: AC's Techshots
description: Technical notes and titbits of everyday programmer's life.
url: https://chakrabar.github.io
author: Arghya C

tumbnail_src: https://chakrabar.github.io/assets/images/github_profile.png